/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateSampleProjectArgs } from "./CreateSampleProjectArgs";
import { UpdateSampleProjectArgs } from "./UpdateSampleProjectArgs";
import { DeleteSampleProjectArgs } from "./DeleteSampleProjectArgs";
import { SampleProjectFindManyArgs } from "./SampleProjectFindManyArgs";
import { SampleProjectFindUniqueArgs } from "./SampleProjectFindUniqueArgs";
import { SampleProject } from "./SampleProject";
import { User } from "../../user/base/User";
import { SampleProjectService } from "../sampleProject.service";

@graphql.Resolver(() => SampleProject)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class SampleProjectResolverBase {
  constructor(
    protected readonly service: SampleProjectService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "SampleProject",
    action: "read",
    possession: "any",
  })
  async _sampleProjectsMeta(
    @graphql.Args() args: SampleProjectFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [SampleProject])
  @nestAccessControl.UseRoles({
    resource: "SampleProject",
    action: "read",
    possession: "any",
  })
  async sampleProjects(
    @graphql.Args() args: SampleProjectFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<SampleProject[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "SampleProject",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => SampleProject, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SampleProject",
    action: "read",
    possession: "own",
  })
  async sampleProject(
    @graphql.Args() args: SampleProjectFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<SampleProject | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "SampleProject",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => SampleProject)
  @nestAccessControl.UseRoles({
    resource: "SampleProject",
    action: "create",
    possession: "any",
  })
  async createSampleProject(
    @graphql.Args() args: CreateSampleProjectArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<SampleProject> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "SampleProject",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"SampleProject"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => SampleProject)
  @nestAccessControl.UseRoles({
    resource: "SampleProject",
    action: "update",
    possession: "any",
  })
  async updateSampleProject(
    @graphql.Args() args: UpdateSampleProjectArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<SampleProject | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "SampleProject",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"SampleProject"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SampleProject)
  @nestAccessControl.UseRoles({
    resource: "SampleProject",
    action: "delete",
    possession: "any",
  })
  async deleteSampleProject(
    @graphql.Args() args: DeleteSampleProjectArgs
  ): Promise<SampleProject | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SampleProject",
    action: "read",
    possession: "any",
  })
  async user(
    @graphql.Parent() parent: SampleProject,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
